name: Labels

on:
  workflow_dispatch:
    inputs:

jobs:
  see-labels:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Show labels
        run: |
          echo "TAG: git describe --tags"
          git describe --tags
          echo "COMMIT: git describe --always"
          git describe --always
