name: Labels

on:
  workflow_dispatch:
    inputs:

jobs:
  see-labels:
    runs-on: ubuntu-18.04
    steps:
      - name: Show labels
        run: |
          echo "TAG: git describe --tags"
          git describe --tags
          echo "COMMIT: git describe --always"
          git describe --always
